- hosts: all
  become: true
  tasks:
    - name: Instalar Apache
      apt:
          update_cache: yes 
          name: apache2           
          state: present
    - name: Instalar MySQL con sus dependencias
      apt:
          update_cache: yes
          name: {{item}}
          state: present 
          with_items:
          - mysql-server-5.7
          - python-pymysql
    - name: Comprobar que los servicios están funcionando
      service:
          name: {{item}}
          state: started          
          with_items:
            - apache2
            - mysql
    - name: Crear el usuario Pepe en MySQL con los permisos adecuados
      mysql_user:
          name: pepe
          password: 123456
          priv: *.*.ALL
