
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "public_network"

  

  config.vm.provision "ansible" do |ansible|
     ansible.playbook = "playbook.yml"
     #ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }      
  end
  
end
